### PR TITLE
Feature/add frontend pipeline

### PR DESCRIPTION
**Pull request by kseniyashaydurova**
Add separate frontend pipeline (the same as we have on saritasa-rocks cluster)

### CODE REVIEW

**Review by dmitry-mightydevops — APPROVED** [review]

**Comment by dmitry-mightydevops** [comment]
@kseniyashaydurova Approved, but it has conflicts - see above. Please resolve.

**Review by populov — APPROVED** [review]

**Review by SergeyDeminSaritasa — APPROVED** [review]

**Comment by dmitry-mightydevops** [comment]
Have you resolved conflicts? And this one still has open state? Close it or merge it?

**Review by DanilaKazakevich — APPROVED** [review]

**Comment by dmitry-mightydevops** [comment]
@kseniyashaydurova  pls resolve conflicts and merge or close it.

**Comment by kseniyashaydurova** [comment]
Closed PR, cause it is not actual anymore and all required changes for `frontend` build are already exist in main

**Pull request closed without merging**
