### PR TITLE
fix: added buildpacks-jekyll to resources list

### PR DESCRIPTION
**Pull request by MikhailKorol-saritasa**
fix: added buildpacks-jekyll to tekton-pipelines resource list

### CODE REVIEW

**Review by dmitry-mightydevops — COMMENTED** [review]
# Approved. 

However I don't see new release
image

**Comment by dmitry-mightydevops** [comment]
Latest I see is https://github.com/saritasa-nest/saritasa-devops-tekton/releases/tag/0.27.0-update1 
so yours should be `0.27.0-update2`

**Comment by MikhailKorol-saritasa** [comment]
@dmitry-mightydevops do we need release instead tag?
as we have new functionality, can we use 0.27.1 tag for direct implementation and 0.27.1-update1 for fix (in future cases, for current 0.27.1)

**Comment by dmitry-mightydevops** [comment]
@MikhailKorol-saritasa 
we should make release for each version that is planned to be deployed. So it's not instead - it's in addition to tag. Github forces you to map release to an existing tag in the repo. 

So if you plan to deploy your code - then a formal release is required.

**Pull request merged**
